/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.SellerIncome;
import co.unicauca.openmarket.client.domain.User;
import co.unicauca.openmarket.client.domain.services.CategoryService;
import co.unicauca.openmarket.client.domain.services.LocationService;
import co.unicauca.openmarket.client.domain.services.ProductService;
import co.unicauca.openmarket.client.domain.services.SellerIncomeService;
import co.unicauca.openmarket.client.domain.services.ShoppingService;
import co.unicauca.openmarket.client.domain.services.UserService;
import co.unicauca.openmarket.client.infra.Messages;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class GUILogin extends javax.swing.JFrame {
    
    private UserService userService;
    private ProductService productService;
    private CategoryService categoryService;
    private LocationService locationService;
    private ShoppingService shoppingService;
    private SellerIncomeService sellerIncomeService;
    private User userLogin;

    /**
     * Creates new form GUILogin
     */
    public GUILogin(UserService userService, ProductService productService,
            CategoryService categoryService, LocationService locationService, ShoppingService shoppingService, 
            SellerIncomeService sellerIncomeService) {
        initComponents();
        this.userService = userService;
        this.productService = productService;
        this.categoryService = categoryService;
        this.locationService = locationService;
        this.shoppingService = shoppingService;
        this.sellerIncomeService = sellerIncomeService;
        userLogin = new User();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlabelUsername = new javax.swing.JLabel();
        jlabelPassword = new javax.swing.JLabel();
        jtxtUsername1 = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonLoginInvitado = new javax.swing.JButton();
        jlabelUsername2 = new javax.swing.JLabel();
        jPasswordFieldUser = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARKET PLACE");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Inicio de sesión");

        jlabelUsername.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlabelUsername.setText("Username:");

        jlabelPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlabelPassword.setText("Password:");

        jButtonLogin.setText("Iniciar sesión");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonLoginInvitado.setText("Iniciar como invitado");
        jButtonLoginInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginInvitadoActionPerformed(evt);
            }
        });

        jlabelUsername2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlabelUsername2.setText("Si no estás registrado puedes iniciar como invitado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldUser)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jlabelUsername)
                            .addComponent(jlabelPassword)
                            .addComponent(jButtonLogin)
                            .addComponent(jButtonLoginInvitado)
                            .addComponent(jlabelUsername2))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtxtUsername1)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabelUsername)
                .addGap(59, 59, 59)
                .addComponent(jlabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonLogin)
                .addGap(18, 18, 18)
                .addComponent(jlabelUsername2)
                .addGap(18, 18, 18)
                .addComponent(jButtonLoginInvitado)
                .addGap(0, 45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jtxtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        verifyLogin();
        
    }//GEN-LAST:event_jButtonLoginActionPerformed
    /**
     * Accón para iniciar como invitado 
     * @param evt 
     */
    private void jButtonLoginInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginInvitadoActionPerformed
        try {
            frameUserBuyer(true);
        } catch (Exception ex) {
            Logger.getLogger(GUILogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLoginInvitadoActionPerformed
    
    private void verifyLogin(){
        String username = this.jtxtUsername1.getText().trim();
        String password = this.jPasswordFieldUser.getText();
        
        try {
            userLogin = this.userService.findByUsernameAndPassword(username, password);
            
            if(userLogin!=null){
               Messages.showMessageDialog("Inicio de sesion exitoso"+" Bienvenido: "+username, "Inicio de sesión");
               if(userLogin.getRole().toString().equals("VENDEDOR")){
                   frameUserSeller();
               }else if(userLogin.getRole().toString().equals("COMPRADOR")){
                   frameUserBuyer(false);
               }
            }else{
               Messages.errorMessage("No existe el usuario, verifica credenciales", "Inicio de sesión");
            }
        } catch (Exception ex) {
            Logger.getLogger(GUILogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Funcionalidades 
     */
    
    private void frameUserSeller() throws Exception{
        GuiUserSeller guiUserSeller = new GuiUserSeller(userLogin, productService, categoryService, locationService);
        guiUserSeller.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        guiUserSeller.setVisible(true);
        guiUserSeller.setLocationRelativeTo(null);
    }
    private void frameUserBuyer(boolean isInvited) throws Exception{
        
        GUIUserBuyer guiUserBuyer = new GUIUserBuyer(userLogin, productService, shoppingService,sellerIncomeService, userService, isInvited);
        guiUserBuyer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        guiUserBuyer.setVisible(true);
        guiUserBuyer.setLocationRelativeTo(null);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLoginInvitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldUser;
    private javax.swing.JLabel jlabelPassword;
    private javax.swing.JLabel jlabelUsername;
    private javax.swing.JLabel jlabelUsername2;
    private javax.swing.JTextField jtxtUsername1;
    // End of variables declaration//GEN-END:variables

   


}
