/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.SellerIncome;
import co.unicauca.openmarket.client.domain.User;
import co.unicauca.openmarket.client.domain.services.CategoryService;
import co.unicauca.openmarket.client.domain.services.LocationService;
import co.unicauca.openmarket.client.domain.services.ProductService;
import co.unicauca.openmarket.client.domain.services.SellerIncomeService;
import co.unicauca.openmarket.client.domain.services.ShoppingService;
import co.unicauca.openmarket.client.domain.services.UserService;
import co.unicauca.openmarket.client.infra.Messages;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class GUILogin extends javax.swing.JFrame {
    
    private UserService userService;
    private ProductService productService;
    private CategoryService categoryService;
    private LocationService locationService;
    private ShoppingService shoppingService;
    private SellerIncomeService sellerIncomeService;
    private User userLogin;

    /**
     * Creates new form GUILogin
     */
    public GUILogin(UserService userService, ProductService productService,
            CategoryService categoryService, LocationService locationService, ShoppingService shoppingService, 
            SellerIncomeService sellerIncomeService) {
        initComponents();
        this.userService = userService;
        this.productService = productService;
        this.categoryService = categoryService;
        this.locationService = locationService;
        this.shoppingService = shoppingService;
        this.sellerIncomeService = sellerIncomeService;
        userLogin = new User();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlabelUsername = new javax.swing.JLabel();
        jlabelPassword = new javax.swing.JLabel();
        jtxtUsername1 = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonLoginInvitado = new javax.swing.JButton();
        jlabelUsername2 = new javax.swing.JLabel();
        jPasswordFieldUser = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);

        jPanel2.setBackground(new java.awt.Color(0, 70, 144));

        jPanel1.setBackground(new java.awt.Color(0, 157, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");

        jlabelUsername.setBackground(new java.awt.Color(255, 255, 255));
        jlabelUsername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jlabelUsername.setText("Username:");

        jlabelPassword.setBackground(new java.awt.Color(255, 255, 255));
        jlabelPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jlabelPassword.setText("Password:");

        jButtonLogin.setBackground(new java.awt.Color(0, 70, 144));
        jButtonLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Iniciar sesión");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonLoginInvitado.setBackground(new java.awt.Color(0, 70, 144));
        jButtonLoginInvitado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonLoginInvitado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoginInvitado.setText("Iniciar como invitado");
        jButtonLoginInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginInvitadoActionPerformed(evt);
            }
        });

        jlabelUsername2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlabelUsername2.setForeground(new java.awt.Color(255, 255, 255));
        jlabelUsername2.setText("Si no estás registrado inicia como invitado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelUsername2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelUsername)
                    .addComponent(jtxtUsername1)
                    .addComponent(jlabelPassword)
                    .addComponent(jPasswordFieldUser)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLoginInvitado))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jlabelUsername)
                .addGap(7, 7, 7)
                .addComponent(jtxtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jlabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin)
                .addGap(18, 18, 18)
                .addComponent(jlabelUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoginInvitado)
                .addGap(28, 28, 28))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARKET PLACE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        verifyLogin();
        
    }//GEN-LAST:event_jButtonLoginActionPerformed
    /**
     * Accón para iniciar como invitado 
     * @param evt 
     */
    private void jButtonLoginInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginInvitadoActionPerformed
        try {
            frameUserBuyer(true);
        } catch (Exception ex) {
            Logger.getLogger(GUILogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLoginInvitadoActionPerformed
    
    private void verifyLogin(){
        String username = this.jtxtUsername1.getText().trim();
        String password = this.jPasswordFieldUser.getText();
        
        try {
            userLogin = this.userService.findByUsernameAndPassword(username, password);
            
            if(userLogin!=null){
               Messages.showMessageDialog("Inicio de sesion exitoso"+" Bienvenido: "+username, "Inicio de sesión");
               if(userLogin.getRole().toString().equals("VENDEDOR")){
                   frameUserSeller();
               }else if(userLogin.getRole().toString().equals("COMPRADOR")){
                   frameUserBuyer(false);
               }
            }else{
               Messages.errorMessage("No existe el usuario, verifica credenciales", "Inicio de sesión");
            }
        } catch (Exception ex) {
            Logger.getLogger(GUILogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Funcionalidades 
     */
    
    private void frameUserSeller() throws Exception{
        GuiUserSeller guiUserSeller = new GuiUserSeller(userLogin, productService, categoryService, locationService);
        guiUserSeller.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        guiUserSeller.setVisible(true);
        guiUserSeller.setLocationRelativeTo(null);
    }
    private void frameUserBuyer(boolean isInvited) throws Exception{
        
        GUIUserBuyer guiUserBuyer = new GUIUserBuyer(userLogin, productService, shoppingService,sellerIncomeService, userService, isInvited);
        guiUserBuyer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        guiUserBuyer.setVisible(true);
        guiUserBuyer.setLocationRelativeTo(null);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLoginInvitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldUser;
    private javax.swing.JLabel jlabelPassword;
    private javax.swing.JLabel jlabelUsername;
    private javax.swing.JLabel jlabelUsername2;
    private javax.swing.JTextField jtxtUsername1;
    // End of variables declaration//GEN-END:variables

   


}
