package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.Category;
import co.unicauca.openmarket.client.domain.Location;
import co.unicauca.openmarket.client.domain.Product;
import co.unicauca.openmarket.client.domain.Shopping;
import co.unicauca.openmarket.client.domain.User;
import co.unicauca.openmarket.client.domain.services.CategoryService;
import co.unicauca.openmarket.client.domain.services.LocationService;
import co.unicauca.openmarket.client.domain.services.ProductService;
import co.unicauca.openmarket.client.domain.services.SellerIncomeService;
import co.unicauca.openmarket.client.domain.services.ShoppingService;
import co.unicauca.openmarket.client.domain.services.UserService;
import co.unicauca.openmarket.client.infra.Messages;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Personal
 */
public class GUIUserBuyer extends javax.swing.JFrame {
    
    private User user;
    private ProductService productService;
    private ShoppingService shoppingService;
    private SellerIncomeService sellerIncomeService;
    private UserService userService;
    private boolean isIvited;
    private List<Product> lstProducts;
    int FilaSelec = -1;
             
    /**
     * Creates new form GuiUserSeller
     */
    public GUIUserBuyer(User user, ProductService productService,ShoppingService shoppingService,
            SellerIncomeService sellerIncomeService,UserService userService, boolean isInvited) {
        
        initComponents();
        this.user = user;
        this.productService = productService;
        this.shoppingService = shoppingService;
        this.lstProducts = new ArrayList<>();
        this.sellerIncomeService = sellerIncomeService;
        this.userService = userService;
        this.isIvited = isInvited;
        llenarTablaProductos(null);
        verifyIsInvited();
    }
    private void verifyIsInvited(){
        if(this.isIvited == true){
            this.jButtonComprarProducto.setVisible(false);
        }
    }
    /**
     * Metodo para cargar la tabla de productos 
     * @param lstProducts 
     */
    private void llenarTablaProductos(List<Product> lstProducts) {
            this.lstProducts = lstProducts == null ? productService.findAllProducts() : lstProducts ; 
            Object matriz [][] = new Object [this.lstProducts.size()][6];
            for(int i=0;i<this.lstProducts.size();i++) {
                matriz [i][0] = this.lstProducts.get(i).getProductId();
                matriz [i][1] = this.lstProducts.get(i).getName();
                matriz [i][2] = this.lstProducts.get(i).getDescription();
                matriz [i][3] = this.lstProducts.get(i).getPrice();
//                matriz [i][4] = this.lstProducts.get(i).getState();
                matriz [i][4] = this.lstProducts.get(i).getStock();
                matriz [i][5] = this.lstProducts.get(i).getUserSellerId();
//                matriz [i][7] = this.lstProducts.get(i).getLocation();
            }
            this.jTableProductos.setModel(new DefaultTableModel(
                matriz,
                new String [] {"ID","Nombre", "Descripción", "Precio", "Stock disponible", "Vendedor"}
            )); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonComprarProducto = new javax.swing.JButton();
        jButtonUpdateTable = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jPanelCenter.setBackground(new java.awt.Color(0, 157, 243));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Precio", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Busqueda:");

        jButtonSearch.setBackground(new java.awt.Color(0, 70, 144));
        jButtonSearch.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setText("Buscar");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Listado de productos disponibles!");

        jButtonComprarProducto.setBackground(new java.awt.Color(0, 70, 144));
        jButtonComprarProducto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonComprarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonComprarProducto.setText("Comprar producto seleccionado");
        jButtonComprarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarProductoActionPerformed(evt);
            }
        });

        jButtonUpdateTable.setBackground(new java.awt.Color(0, 70, 144));
        jButtonUpdateTable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonUpdateTable.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdateTable.setText("Actualizar tabla");
        jButtonUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(255, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanelCenterLayout.createSequentialGroup()
                                .addComponent(jButtonComprarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonUpdateTable, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonSearch))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComprarProducto)
                    .addComponent(jButtonUpdateTable))
                .addGap(30, 30, 30))
        );

        jPanel1.setBackground(new java.awt.Color(0, 157, 243));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARKET PLACE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción del boton de comprar productos
     * @param evt evento que dispara la acción
     */
    private void jButtonComprarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarProductoActionPerformed
        try {
            // TODO add your handling code here:
            buyProduct();
        } catch (Exception ex) {
            Logger.getLogger(GUIUserBuyer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonComprarProductoActionPerformed

    /**
     * Acción del boton para realizar una búsqueda por nombre y descripción
     * @param evt evento que dispara la acción.
     */
    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String search = this.jTextFieldSearch.getText().trim();
        searchProducts(search);
    }//GEN-LAST:event_jButtonSearchActionPerformed
    /**
     * Acción del boton que actualiza la tabla de productos. 
     * @param evt 
     */
    private void jButtonUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateTableActionPerformed
        // TODO add your handling code here:
        llenarTablaProductos(null);
    }//GEN-LAST:event_jButtonUpdateTableActionPerformed

    
    /**
     * Funcionalidades 
     */
    private void searchProducts(String search){
        //busqueda por name y description
        this.lstProducts = this.productService.findAllByNameAndDescription(search);
        //actulizo la tabla
        llenarTablaProductos(this.lstProducts);
    }
    private void  buyProduct() throws Exception{
        Product product = new Product();
        product = productSelected();
        if(this.FilaSelec != -1){
           Shopping shopping = new Shopping();
           shopping.setUserBuyerId(this.user.getUserId());
           shopping.setProductId(product.getProductId());
           //Pasarela de pago
           callJDialogPayment(shopping, product);
//           this.shoppingService.save(shopping);
            //la fila seleccionada se limpia
            this.FilaSelec = -1;
        }else{
            Messages.warningMessage("ERROR! no ha seleccionado ninguna fila de la tabla", "Comprar producto");
        }
    }
    
    private void callJDialogPayment(Shopping shopping, Product product){
        JDialogPaymentgateway objJDialogPayment = new JDialogPaymentgateway(this,false,this.shoppingService, this.productService, 
                this.sellerIncomeService, this.userService, shopping, user, product.getPrice());
         objJDialogPayment.setVisible(true);
        objJDialogPayment.setLocationRelativeTo(null);
    }
     /**
     * Metodo para obtener los valores de una fila de la tabla correspondientes a un producto. 
     * @return 
     */
    public Product productSelected() {//posible modificacion
        FilaSelec = this.jTableProductos.getSelectedRow();
        Product product = new Product();
        if (FilaSelec >= 0) {
            product.setProductId(Long.parseLong(this.jTableProductos.getValueAt(FilaSelec, 0).toString()));
            product.setName(this.jTableProductos.getValueAt(FilaSelec, 1).toString());
            product.setDescription(this.jTableProductos.getValueAt(FilaSelec, 2).toString());
            product.setPrice(Double.parseDouble(this.jTableProductos.getValueAt(FilaSelec, 3).toString()));
            product.setStock(Integer.parseInt(this.jTableProductos.getValueAt(FilaSelec, 4).toString()));
            product.setUserSellerId(Long.parseLong(this.jTableProductos.getValueAt(FilaSelec, 5).toString()));
        }
        return product;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprarProducto;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
