/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.Product;
import co.unicauca.openmarket.client.domain.SellerIncome;
import co.unicauca.openmarket.client.domain.Shopping;
import co.unicauca.openmarket.client.domain.User;
import co.unicauca.openmarket.client.domain.services.ProductService;
import co.unicauca.openmarket.client.domain.services.SellerIncomeService;
import co.unicauca.openmarket.client.domain.services.ShoppingService;
import co.unicauca.openmarket.client.domain.services.UserService;
import co.unicauca.openmarket.client.infra.Messages;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class JDialogPaymentgateway extends javax.swing.JDialog {
    
    private ShoppingService shoppingService;
    private ProductService productService;
    private SellerIncomeService sellerIncomeService;
    private UserService userService;
    private Shopping shopping; 
    private User user;

    /**
     * Creates new form JDialogPaymentgateway
     */
    public JDialogPaymentgateway(java.awt.Frame parent, boolean modal, ShoppingService shoppingService, 
            ProductService productService, SellerIncomeService sellerIncomeService, UserService userService, 
            Shopping shopping, User user, Double price) {
        super(parent, modal);
        this.shoppingService = shoppingService;
        this.productService = productService;
        this.sellerIncomeService = sellerIncomeService;
        this.userService = userService;
        this.shopping = shopping;
        this.user = user;
        initComponents();
        this.jLabelTotalPagar.setText(price.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumeroCuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelTotalPagar = new javax.swing.JLabel();
        jComboBoxTipoCuenta = new javax.swing.JComboBox<>();
        jButtonConfirmarPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 157, 243));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PASARELA DE PAGO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelCenter.setBackground(new java.awt.Color(0, 157, 243));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de cedula:");

        jTextFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de cuenta:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número de cuenta");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total a pagar:");

        jComboBoxTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corriente", "Ahorros", "Credito", "Debido" }));

        jButtonConfirmarPago.setBackground(new java.awt.Color(0, 70, 144));
        jButtonConfirmarPago.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonConfirmarPago.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConfirmarPago.setText("Confirmar pago");
        jButtonConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCedula)
                    .addComponent(jTextFieldNumeroCuenta)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanelCenterLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTotalPagar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBoxTipoCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jButtonConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelTotalPagar))
                .addGap(36, 36, 36)
                .addComponent(jButtonConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed
    /**
     * Acción del boton para confirmar pago. 
     * @param evt evento que dispara la accion
     */
    private void jButtonConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarPagoActionPerformed
       paymentProduct();
    }//GEN-LAST:event_jButtonConfirmarPagoActionPerformed

    /**
     * Metodo para realizar el pago del producto. 
     */
    private void paymentProduct() {
        if (!this.jTextFieldCedula.getText().equals("") && !this.jTextFieldNumeroCuenta.getText().equals("")) {
            try {
                //TODO guardar compra.
                this.shoppingService.save(this.shopping);
                //TODO 2. actualizar el stock.
                //TODO 2.1. buscar el producto
                Product product = this.productService.findProductById(shopping.getProductId());
                System.out.println("id: " + product.getProductId());
                System.out.println("id: " + product.getName());
                System.out.println("id: " + product.getDescription());
                System.out.println("estadoooo: " + product.getState());
                System.out.println("id: " + product.getPrice());
                System.out.println("id: " + product.getStock());
                System.out.println("id: " + product.getCategoryId());
                System.out.println("id: " + product.getUserSellerId());
                product.setStock(product.getStock() - 1);
                //TODO 2.3 Actualizar el stock del producto
                this.productService.editProduct(product);

                Shopping shoppingFind = this.shoppingService.findByProductId(product.getProductId());

                //TODO 3. guardar la comisión en la tabla SellerIncome del vendedor.
                Double commission = 0.12 * product.getPrice();
                SellerIncome sellerIncome = new SellerIncome();
                sellerIncome.setIncome(product.getPrice() - commission);
                sellerIncome.setShoppingId(shoppingFind.getShoppingId());

                boolean bandera = this.sellerIncomeService.save(sellerIncome);

                //TODO 4. Llamar a un jDialog para la puntuación.
                int result = JOptionPane.showConfirmDialog(this, "¿Deseas calificar al vendedor? ", "Calificación servicio", JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {
                    if (bandera) {
                        JDialogScore objJDScore = new JDialogScore(this, false, this.userService, product.getUserSellerId());
                        objJDScore.setVisible(true);
                        objJDScore.setLocationRelativeTo(null);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Compra realizada exitosamente ", "Compra producto", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }

            } catch (Exception ex) {
                Logger.getLogger(JDialogPaymentgateway.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes digitar todos los campos", "Compra producto", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarPago;
    private javax.swing.JComboBox<String> jComboBoxTipoCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotalPagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
